### ISSUE TITLE
Feature Request: Continue plotting while moving previous plot

### ISSUE THREAD

**Issue by Freekers** [SamuelNZ/SPlotter#5]
Currently, plotting is paused while moving the previous plot. Is it possible to add a feature to override this and continue plotting while moving the previous plot in the background?

**Comment by SamuelNZ** [comment]
Add -RADW 1 to your configs and it will move the last plot while it makes the next one.

It's not recommended you do this unless you are plotting on an SSD or NVMe and then moving plots because once you have a couple of plots moving in the background things get a bit slow, to say the least.

You can only see the last plot that started moving, Even if there are 5 in the background.
